config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'messages/new'
  get 'messages/index'
  get 'rooms/index'
  get 'chats/show'
  get 'ratings/new'
  get 'ratings/create'
  get 'ratings/update'
  # get 'comments/create'
  # get 'comments/destroy'
  root to: "homes#index"
  get 'appointments/new'
  get 'appointments/create'
  get 'posts/new'
  get 'posts/create'
  get 'posts/show'

  get '/clients/:client_id/My_Trainers', to: 'clients#show_trainers', as: "my_trainers"
  get "/client/:client_id", to: "chats#private_chat", as: "client_private_chat"
  get "/trainer/:trainer_id", to: "chats#private_chat", as: "trainer_private_chat"
  devise_for :users
  
  # devise_scope :users do
  #    get 'users/:id', to: 'registrations#show', as: 'user'
  # end

 resources :rooms do
  resources :messages
 end
  
resources :clients
# resources :trainers
resources :trainers do
  resources :appointments
  resources :ratings
  resources :posts do
    resources :comments
  end
end

  # resources :trainers do
    
  # end

  resources :appointments, only: [] do
    member do
      get :confirm
      delete :reject
      delete :cancel
    end
  end
  get '/trainers/:trainer_id/Pending_Appointments', to: 'trainers#show_pendings', as: "pending_appointments"
  get '/trainers/:trainer_id/My_Clients', to: 'trainers#show_clients', as: "my_clients"
  delete '/trainers/sign_out', to: 'devise/sessions#destroy', as: :trainers_sign_out
  
  get 'user/:id', to: 'trainers#show', as: 'user'
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
 
  # Defines the root path route ("/")
  # root "articles#index"
  
end

app/models/ability.rb
class Ability
  include CanCan::Ability
  def initialize(user)
    if user.client?
      can :manage, Client
      can :read, Trainer
      can [:create, :update], Rating
      can [:create, :read, :destroy], Comment
      can :create, Appointment
    elsif user.trainer?
      can :manage, Trainer
      can :manage, Post
      can [:read, :destroy], Comment
      can :read, Client
      can [:confirm, :reject], Appointment
    end
  end
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :client
  belongs_to :trainer
end

app/models/client.rb
class Client < ApplicationRecord
  belongs_to :user
  has_many :appointments, dependent: :destroy
  has_many :ratings, dependent: :destroy
  has_many :rated_trainers, through: :ratings, source: :trainer
  has_one_attached :profile
  
  validates :name, presence: true, uniqueness: true
  validates :phone_number, numericality: true, length: { is: 10, messages: "phone number must contain 10 digits" }
  validates :age, numericality: true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  validates :comment, presence: true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room
  after_create_commit { broadcast_append_to self.room }
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :trainer
  has_many :comments, dependent: :destroy
  has_many_attached :images
  validates :title, presence: true
end

app/models/rating.rb
class Rating < ApplicationRecord
  belongs_to :client
  belongs_to :trainer
end

app/models/room.rb
class Room < ApplicationRecord
  validates_uniqueness_of :name
  scope :public_rooms, -> { where(is_private: false) }
  after_create_commit { broadcast_append_to "rooms" }
  has_many :messages, dependent: :destroy

end

app/models/trainer.rb
class Trainer < ApplicationRecord
  belongs_to :user
  has_many :posts, dependent: :destroy
  has_many :appointments, dependent: :destroy
  has_one_attached :profile
  has_many :ratings, class_name: "Rating", dependent: :destroy
  has_many :rating_clients, through: :ratings, source: :client
  
  validates :name, presence: true, uniqueness: true
  validates :phone_number, numericality: true, length: { is: 10, messages: "phone number must contain 10 digits" }
  validates :age, numericality: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  scope :all_except, ->(user) { where.not(id: user) }
  after_create_commit { broadcast_append_to "users" }
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable
         
  enum role: {client: 0, trainer: 1}

  has_one :trainer, dependent: :destroy
  has_one :client, dependent: :destroy
  has_many :messages, dependent: :destroy
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_client, only: [:show, :show_trainers]
  load_and_authorize_resource
  
  def index
    @clients = Client.all.paginate(page: params[:page], per_page: 5)
    
  end

  def show
     # @client is already set in the before_action callback
  end

  def new
    @client = current_user.build_client
  end

  def create
    @client = current_user.build_client(client_params)
    if @client.save
      redirect_to client_path(current_user)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @client = Client.find(params[:id])
  end

  def update
    @client = Client.find(params[:id])
    if @client.update(client_params)
      redirect_to @client, notice: 'Client was successfully updated.'
    else
      render :edit
    end
  end

  def show_trainers
    @all_trainers = Trainer.includes(appointments: :client).where("appointments.client_id =?", @client.id).references(:client)
  end

  def destroy
  end

  private

  def client_params
    params.require(:client).permit(:name, :age, :phone_number, :profile)
  end

  def set_client
    if current_user.client?
      @client = current_user.client
      
    else
      @client = Client.find(params[:id])
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/trainers_helper.rb
module TrainersHelper
end

app/views/clients/create.html.erb
<h1>Clients#create</h1>
<p>Find me in app/views/clients/create.html.erb</p>

app/views/clients/destroy.html.erb
<h1>Clients#destroy</h1>
<p>Find me in app/views/clients/destroy.html.erb</p>

app/views/clients/edit.html.erb
<h1>Edit Client</h1>

<%= form_with model: [@client] do |c| %>
    <%#= form_with model: [current_user, current_user.build_client] do |c| %>
      <div>
        <%= c.label :Name %>
        <%= c.text_field :name %>
      </div>
    
      <div>
        <%= c.label :Age %>
        <%= c.text_field :age %>
      </div>
    
      <div>
        <%= c.label "Phone Number" %>
        <%= c.text_field :phone_number %>
      </div>
    
      <div class="field">
        <%= c.label "Profile Picture" %>
        <%= c.file_field :profile, multiple: false %>
      </div>

      <div>
        <%= c.submit %>
      </div>
<% end %>

<%= link_to 'Show', @client %> |
<%= link_to 'Back', @client %>

app/views/clients/index.html.erb
<h1>Clients</h1>

<ul>
  <% @clients.each do |client| %>
    <div style="display: flex; align-items: center;">
      <%= image_tag(client.profile, size: "170x180", style: 'border-radius: 50%;', class: 'css_class') %>
      <div style="margin-left: 10px;">
        <p>Name: <%= client.name.capitalize %></p>
        <%= link_to "View Profile", client_path(client) %>
      </div>
    </div>
  <% end %>
</ul>
<%= link_to "Back to your profile", trainer_path(current_user) %>

<div class="text-center">
  <div class="digg_pagination">
    <div class="page_info">
      <%= will_paginate @clients %>
    </div>
  </div>
</div>

app/views/clients/new.html.erb
<h1>Please Create Your Client Profile</h1>
<%= form_with model: [@client] do |c| %>
<%#= form_with model: [current_user, current_user.build_client] do |c| %>
  <div>
    <%= c.label :Name %>
    <%= c.text_field :name %>
  </div>

  <div>
    <%= c.label :Age %>
    <%= c.text_field :age %>
  </div>

  <div>
    <%= c.label "Phone Number" %>
    <%= c.text_field :phone_number %>
  </div>

  <div class="field">
    <%= c.label "Profile Picture" %>
    <%= c.file_field :profile, multiple: false %>
  </div>

  <div>
    <%= c.submit %>
  </div>
<% end %>

app/views/clients/show.html.erb
<style>
  .chat-button{
    background-color: lightblue;
    color: white;
    padding: 10px 10px;
    text-align: center;
    text-decoration: none;
    display: inline-block;
    font-size: 10px;
    border-radius: 10px
  }
</style>

<div style="margin-left: 2rem ; margin-top: 2rem; width: 100%">
  <% if @client.profile.attached? %>
    <%= image_tag(@client.profile,size: "170x180", style: 'border-radius: 50%;', class: 'css_class') %>
  <% end %>

  <div style="line-height: 10px">
    <h1><%= @client.name %></h1>
    <p>Age: <%= @client.age %></p>
    <p>Phone Number: <%= @client.phone_number %></p>
  </div>

  <% if current_user.trainer? and current_user.trainer.appointments.exists?(client_id: @client.id) %>
    <% appointment = current_user.trainer.appointments.find_by(client_id: @client.id, trainer_id: current_user.trainer.id) %>
    <% if appointment.present? %>
      <% if appointment.confirmed.nil? %>
        <p>Please wait for the trainer to confirm your appointment.</p>
      <% elsif appointment.confirmed? and appointment.trainer_id == current_user.trainer.id %>
      <p>Hello <%= current_user.trainer.name %>, drop your message...<%= link_to "Chat", client_private_chat_path(@client.id), class: "chat-button" %></p><br />
      <% end %>
    <% end %>
  <% end %>

  <% if current_user.role == "client" %>
    <%= link_to 'Edit Your Profile', edit_client_path(@client) %> <br>
    <%= link_to "My Trainers", my_trainers_path(@client) %> <br>
    <%= link_to "All Trainers", trainers_path %>
    <%= button_to "Log Out", destroy_user_session_path, method: :delete, data: { confirm: "Are you sure you want to log out?" } %>
  <% end %>
  <% if current_user.role == "trainer" %>
    <%= link_to "Back to Feeds", clients_path %><br>
  <% end %>
</div>

app/views/clients/show_trainers.html.erb
<ul>
<div>
  <% @all_trainers.each do |t| %>

    <li><p>Name: <%= link_to t.name, trainer_path(t) %></p></li><br>
  <% end %>
</div>
</ul>

<%= link_to 'Back to Profile', client_path(@client.id) %>

app/views/clients/update.html.erb
<h1>Clients#update</h1>
<p>Find me in app/views/clients/update.html.erb</p>