config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'messages/new'
  get 'messages/index'
  get 'rooms/index'
  get 'chats/show'
  get 'ratings/new'
  get 'ratings/create'
  get 'ratings/update'
  # get 'comments/create'
  # get 'comments/destroy'
  root to: "homes#index"
  get 'appointments/new'
  get 'appointments/create'
  get 'posts/new'
  get 'posts/create'
  get 'posts/show'

  get '/clients/:client_id/My_Trainers', to: 'clients#show_trainers', as: "my_trainers"
  get "/client/:client_id", to: "chats#private_chat", as: "client_private_chat"
  get "/trainer/:trainer_id", to: "chats#private_chat", as: "trainer_private_chat"
  devise_for :users
  
  # devise_scope :users do
  #    get 'users/:id', to: 'registrations#show', as: 'user'
  # end

 resources :rooms do
  resources :messages
 end
  
resources :clients
# resources :trainers
resources :trainers do
  resources :appointments
  resources :ratings
  resources :posts do
    resources :comments
  end
end

  # resources :trainers do
    
  # end

  resources :appointments, only: [] do
    member do
      get :confirm
      delete :reject
      delete :cancel
    end
  end
  get '/trainers/:trainer_id/Pending_Appointments', to: 'trainers#show_pendings', as: "pending_appointments"
  get '/trainers/:trainer_id/My_Clients', to: 'trainers#show_clients', as: "my_clients"
  delete '/trainers/sign_out', to: 'devise/sessions#destroy', as: :trainers_sign_out
  
  get 'user/:id', to: 'trainers#show', as: 'user'
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
 
  # Defines the root path route ("/")
  # root "articles#index"
  
end

app/models/ability.rb
class Ability
  include CanCan::Ability
  def initialize(user)
    if user.client?
      can :manage, Client
      can :read, Trainer
      can [:create, :update], Rating
      can [:create, :read, :destroy], Comment
      can :create, Appointment
    elsif user.trainer?
      can :manage, Trainer
      can :manage, Post
      can [:read, :destroy], Comment
      can :read, Client
      can [:confirm, :reject], Appointment
    end
  end
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :client
  belongs_to :trainer
end

app/models/client.rb
class Client < ApplicationRecord
  belongs_to :user
  has_many :appointments, dependent: :destroy
  has_many :ratings, dependent: :destroy
  has_many :rated_trainers, through: :ratings, source: :trainer
  has_one_attached :profile
  
  validates :name, presence: true, uniqueness: true
  validates :phone_number, numericality: true, length: { is: 10, messages: "phone number must contain 10 digits" }
  validates :age, numericality: true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  validates :comment, presence: true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room
  after_create_commit { broadcast_append_to self.room }
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :trainer
  has_many :comments, dependent: :destroy
  has_many_attached :images
  validates :title, presence: true
end

app/models/rating.rb
class Rating < ApplicationRecord
  belongs_to :client
  belongs_to :trainer
end

app/models/room.rb
class Room < ApplicationRecord
  validates_uniqueness_of :name
  scope :public_rooms, -> { where(is_private: false) }
  after_create_commit { broadcast_append_to "rooms" }
  has_many :messages, dependent: :destroy

end

app/models/trainer.rb
class Trainer < ApplicationRecord
  belongs_to :user
  has_many :posts, dependent: :destroy
  has_many :appointments, dependent: :destroy
  has_one_attached :profile
  has_many :ratings, class_name: "Rating", dependent: :destroy
  has_many :rating_clients, through: :ratings, source: :client
  
  validates :name, presence: true, uniqueness: true
  validates :phone_number, numericality: true, length: { is: 10, messages: "phone number must contain 10 digits" }
  validates :age, numericality: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  scope :all_except, ->(user) { where.not(id: user) }
  after_create_commit { broadcast_append_to "users" }
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable
         
  enum role: {client: 0, trainer: 1}

  has_one :trainer, dependent: :destroy
  has_one :client, dependent: :destroy
  has_many :messages, dependent: :destroy
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user! #to ensure users are signed in to create posts
  before_action :set_trainer, only: [:new, :create, :show, :index, :destroy]
  # load_and_authorize_resource
  def new
    if current_user.role == "client"
      redirect_to client_path(current_user)
    else
      @post = @trainer.posts.new
    end
  end

  def create
    @post = @trainer.posts.new(post_params)
    if @post.save
      redirect_to trainer_post_path(@trainer, @post.id), notice: 'Post was successfully created.'
    else
      render :new
    end
  end

  def show
    @posts = @trainer.posts.paginate(page: params[:page], per_page: 3)
  end

  def index
    @posts = @trainer.posts.all.paginate(page: params[:page], per_page: 3)
  end

    def destroy
    @post = @trainer.posts.find(params[:id])

    if @post.destroy
      redirect_to trainer_path(@trainer), notice: 'Post was successfully deleted.'
    else
      redirect_to trainer_post_path(@trainer, @post), alert: 'Failed to delete the post.'
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :content, images: [])
  end
  def set_trainer
    @trainer = Trainer.find(params[:trainer_id])
  end
end

# test comment

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/trainers_helper.rb
module TrainersHelper
end

app/views/posts/_form.html.erb
<%= form_with(model: [@trainer , @post]) do |form| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, 'error') %> prohibited this post from being saved:</h2>

      <ul>
        <% @post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label "Add Pics" %>
    <%= form.file_field :images, multiple: true %>
  </div>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/create.html.erb
<h1>Posts#create</h1>
<p>Find me in app/views/posts/create.html.erb</p>

app/views/posts/index.html.erb
<% if @posts.size == 0 %>  
    <p>Please create your first post</p><br><%= link_to "Create New Post", new_trainer_post_path(@trainer) %><br>
    <%= link_to 'Back to Profile', trainer_path(@trainer) %>
<% else %>
    <div>
    <% @posts.each do |post| %>
    <li><p>Title: <%= post.title %></p></il>
    <% if post.images.attached? %>
        <% post.images.each do |i| %>
        
        <%= image_tag(i, size: "300x310", style: 'border-radius: 20%;') %>
        <% end %>
    <% end %>
    <li><p>Content: <%= post.content %></p></li><br>
    <li><%= link_to "Destroy", trainer_post_path(@trainer.id,post.id), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                } %></li>
    <%= link_to "comments", trainer_post_comments_path( @trainer.id, post.id  ) %>
    <hr>
    <% end %>
    </div>
<% end %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>


<%= link_to 'Back to Profile', trainer_path(@trainer.id) %>

app/views/posts/show.html.erb
<style>
.stick {
  position: relative;
  bottom: 500px;
  left: 1160px;
}
</style>

<% if @posts.size == 0 %>  
  <% if current_user.role == "trainer" %>
    <p>Please create your first post</p><br><%= link_to "Create New Post", new_trainer_post_path(@trainer) %><br>
    <%= link_to 'Back to Profile', trainer_path(@trainer) %>
  <% else %>
    <p>This trainer currently has no post.</p><br>
    <%= link_to 'Back to Profile', trainer_path(@trainer.id) %>
  <% end %>

<% else  %>
  <ul>
  <% if current_user.role == "trainer" %>
  <div>
    <% @posts.each do |post| %>
      <li><p>Title: <%= post.title %></p></il>
      <% if post.images.attached? %>
        <% post.images.each do |i| %>
        
          <%= image_tag(i, size: "300x310", style: 'border-radius: 20%;') %>
        <% end %>
      <% end %>
      <li><p>Content: <%= post.content %></p></li><br>
      <li><%= link_to "Destroy", trainer_post_path(@trainer.id,post.id), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %></li>
      <%= link_to "comments", trainer_post_comments_path( @trainer.id, post.id  ) %>
      <hr>
    <% end %>
  </div>
  <br>
    <div class = "stick">
    <%= link_to 'Back to Profile', trainer_path(@trainer.id) %>
    </div>
  <% else %>
    <% @posts.each do |post| %>
      <li><p>Title: <%= post.title %></p></il>
      <% if post.images.attached? %>
        <% post.images.each do |i| %>
          <%= image_tag(i, size: "300x310", style: 'border-radius: 20%;') %>
        <% end %>
      <% end %>
      <li><p>Content: <%= post.content %></p></li>
      <h2>Comments</h2>
      <%= link_to "Add Comment", new_trainer_post_comment_path(@trainer.id,post.id)%><br>
      <%= link_to "comments", trainer_post_comments_path( post.trainer.id, post.id  ) %><br>
    <% end %>
    <br>
    <hr>
    <div class = "stick">
    <%= link_to 'Back to Profile', trainer_path(@trainer.id) %>
    </div>
  </ul>
  <% end %>
<% end %>
<div class="text-center">
  <div class="digg_pagination">
    <div class="page_info">
      <%= will_paginate @post %>
    </div>
  </div>
</div>