config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'messages/new'
  get 'messages/index'
  get 'rooms/index'
  get 'chats/show'
  get 'ratings/new'
  get 'ratings/create'
  get 'ratings/update'
  # get 'comments/create'
  # get 'comments/destroy'
  root to: "homes#index"
  get 'appointments/new'
  get 'appointments/create'
  get 'posts/new'
  get 'posts/create'
  get 'posts/show'

  get '/clients/:client_id/My_Trainers', to: 'clients#show_trainers', as: "my_trainers"
  get "/client/:client_id", to: "chats#private_chat", as: "client_private_chat"
  get "/trainer/:trainer_id", to: "chats#private_chat", as: "trainer_private_chat"
  devise_for :users
  
  # devise_scope :users do
  #    get 'users/:id', to: 'registrations#show', as: 'user'
  # end

 resources :rooms do
  resources :messages
 end
  
resources :clients
# resources :trainers
resources :trainers do
  resources :appointments
  resources :ratings
  resources :posts do
    resources :comments
  end
end

  # resources :trainers do
    
  # end

  resources :appointments, only: [] do
    member do
      get :confirm
      delete :reject
      delete :cancel
    end
  end
  get '/trainers/:trainer_id/Pending_Appointments', to: 'trainers#show_pendings', as: "pending_appointments"
  get '/trainers/:trainer_id/My_Clients', to: 'trainers#show_clients', as: "my_clients"
  delete '/trainers/sign_out', to: 'devise/sessions#destroy', as: :trainers_sign_out
  
  get 'user/:id', to: 'trainers#show', as: 'user'
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
 
  # Defines the root path route ("/")
  # root "articles#index"
  
end

app/models/ability.rb
class Ability
  include CanCan::Ability
  def initialize(user)
    if user.client?
      can :manage, Client
      can :read, Trainer
      can [:create, :update], Rating
      can [:create, :read, :destroy], Comment
      can :create, Appointment
    elsif user.trainer?
      can :manage, Trainer
      can :manage, Post
      can [:read, :destroy], Comment
      can :read, Client
      can [:confirm, :reject], Appointment
    end
  end
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :client
  belongs_to :trainer
end

app/models/client.rb
class Client < ApplicationRecord
  belongs_to :user
  has_many :appointments, dependent: :destroy
  has_many :ratings, dependent: :destroy
  has_many :rated_trainers, through: :ratings, source: :trainer
  has_one_attached :profile
  
  validates :name, presence: true, uniqueness: true
  validates :phone_number, numericality: true, length: { is: 10, messages: "phone number must contain 10 digits" }
  validates :age, numericality: true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  validates :comment, presence: true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room
  after_create_commit { broadcast_append_to self.room }
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :trainer
  has_many :comments, dependent: :destroy
  has_many_attached :images
  validates :title, presence: true
end

app/models/rating.rb
class Rating < ApplicationRecord
  belongs_to :client
  belongs_to :trainer
end

app/models/room.rb
class Room < ApplicationRecord
  validates_uniqueness_of :name
  scope :public_rooms, -> { where(is_private: false) }
  after_create_commit { broadcast_append_to "rooms" }
  has_many :messages, dependent: :destroy

end

app/models/trainer.rb
class Trainer < ApplicationRecord
  belongs_to :user
  has_many :posts, dependent: :destroy
  has_many :appointments, dependent: :destroy
  has_one_attached :profile
  has_many :ratings, class_name: "Rating", dependent: :destroy
  has_many :rating_clients, through: :ratings, source: :client
  
  validates :name, presence: true, uniqueness: true
  validates :phone_number, numericality: true, length: { is: 10, messages: "phone number must contain 10 digits" }
  validates :age, numericality: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  scope :all_except, ->(user) { where.not(id: user) }
  after_create_commit { broadcast_append_to "users" }
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable
         
  enum role: {client: 0, trainer: 1}

  has_one :trainer, dependent: :destroy
  has_one :client, dependent: :destroy
  has_many :messages, dependent: :destroy
end

app/controllers/trainers_controller.rb
class TrainersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_trainer, only: [:show, :show_pendings]
  load_and_authorize_resource

  def index
    @trainers = User.where(role: :trainer).joins(:trainer).paginate(page: params[:page], per_page: 3)
  end

  def show
    @ratings = @trainer.ratings  # @trainer is already set in the before_action callback
    if @trainer.nil?
      redirect_to trainers_path, alert: 'Trainer not found.'  # If no trainer found
    end
  end

  def new
    @trainer = current_user.build_trainer
  end

  def create
    @trainer = current_user.build_trainer(trainer_params)
    if @trainer.save
      redirect_to trainer_path(current_user)
    else
      render :new
    end
  end
  
  def show_clients
    @trainer = current_user.trainer
    @all_clients = Client.includes(appointments: :trainer).where("appointments.trainer_id =?", @trainer.id).references(:trainer)
  end

  def show_pendings
    @appointments = Appointment.where('trainer_id = ?', @trainer.id).where(appointments: {confirmed: nil})
  end
  
  def edit
    @trainer = Trainer.find(params[:id])
  end

  def update
    @trainer = Trainer.find(params[:id])
    if @trainer.update(trainer_params)
      redirect_to @trainer, notice: 'trainer was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
  end

  def trainer_params
    params.require(:trainer).permit(:name, :age, :phone_number, :experience, :training_type, :profile)
  end
  
  def set_trainer
    if current_user.client?
      @trainer = Trainer.find(params[:id])
    else
      @trainer = current_user.trainer
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/trainers_helper.rb
module TrainersHelper
end

app/views/trainers/create.html.erb
<h1>Trainers#create</h1>
<p>Find me in app/views/trainers/create.html.erb</p>

app/views/trainers/destroy.html.erb
<h1>Trainers#destroy</h1>
<p>Find me in app/views/trainers/destroy.html.erb</p>

app/views/trainers/edit.html.erb
<h1>Please Create Your Trainer Profile</h1>
<%= form_with model: @trainer do |t| %>
  <div>
    <%= t.label :Name %>
    <%= t.text_field :name %>
  </div>

  <div>
    <%= t.label :Age %>
    <%= t.text_field :age %>
  </div>

  <div>
    <%= t.label "Phone Number" %>
    <%= t.text_field :phone_number %>
  </div>

  <div>
    <%= t.label "Experience" %>
    <%= t.text_field :experience %>
  </div>

  <div>
    <%= t.label "Training Type" %>
    <%= t.text_field :training_type %>
  </div>

  <div class="field">
    <%= t.label "Profile Picture" %>
    <%= t.file_field :profile, multiple: false %>
  </div>

  <div>
    <%= t.submit %>
  </div>
<% end %>

<%= link_to 'Show', @trainer %> |
<%= link_to 'Back', @trainer %>

app/views/trainers/index.html.erb
<h1>Our Trainers</h1>
<ul>
  <% @trainers.each do |trainer_user| %>
    <div style="display: flex; align-items: center;">
      <%= image_tag(trainer_user.trainer.profile, size: "170x180", style: 'border-radius: 50%;', class: 'css_class') %>
      <div style="margin-left: 10px;">
        <p>Name: <%= trainer_user.trainer.name.capitalize %></p>
        <%= link_to "View Profile", trainer_path(trainer_user.trainer) %>
      </div>
    </div>
    <br><br>
    <!-- Add other attributes specific to Trainer model -->
  <% end %>
</ul>
<% if current_user.role == "client" %>
    <%= link_to "Back to your profile", client_path(current_user) %>
<% end %>

<div class="text-center">
  <div class="digg_pagination">
    <div class="page_info">
      <%= will_paginate @trainers %>
    </div>
  </div>
</div>

app/views/trainers/new.html.erb
<h1>Please Create Your Trainer Profile</h1>
<%= form_with model: @trainer do |t| %>
  <% if @trainer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@trainer.errors.count, "error") %> prohibited this trainer from being saved:</h2>
      <ul>
      <% @trainer.errors.full_messages.each do |message| %>
          <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div>
    <%= t.label :Name %>
    <%= t.text_field :name %>
  </div>

  <div>
    <%= t.label :Age %>
    <%= t.text_field :age %>
  </div>

  <div>
    <%= t.label "Phone Number" %>
    <%= t.text_field :phone_number %>
  </div>

  <div>
    <%= t.label "Experience" %>
    <%= t.text_field :experience %>
  </div>

  <div>
    <%= t.label "Training Type" %>
    <%= t.text_field :training_type %>
  </div>

  <div class="field">
    <%= t.label "Profile Picture" %>
    <%= t.file_field :profile, multiple: false %>
  </div>

  <div>
    <%= t.submit %>
  </div>
<% end %>

app/views/trainers/show.html.erb
<style>
  .chat-button{
    background-color: lightblue;
    color: white;
    padding: 10px 10px;
    text-align: center;
    text-decoration: none;
    display: inline-block;
    font-size: 10px;
    border-radius: 10px
  }
</style>


<% @rate = [] %>
<% @ratings.each do |r| %> 
  <% @rate << r.value.to_i %>
<% end %>
<% @my_rating = @rate.sum/@rate.size.to_f %>

<div style="margin-left: 2rem ; margin-top: 2rem; width: 100%">
  <% if @trainer.profile.attached? %>
    <%= image_tag(@trainer.profile,size: "170x180", style: 'border-radius: 50%;', class: 'css_class') %>
  <% end %>

  <h2 style="font-weight: bold">Welcome, I am <%= @trainer.name.capitalize %> </h2>
  <div style="line-height: 10px">
    <p>I am <%= @trainer.age %> years old.</p>
    <p>Training Type: <%= @trainer.training_type %></p>
    <p>Here you can contact me:-<br><li><%= @trainer.phone_number %></li><br><li><%= @trainer.user.email %></li></p>
  </div>

  <% if current_user.client? %>
    <% unless current_user.client.appointments.exists?(trainer_id: @trainer.id) %>
      <%= link_to "Schedule Appointment", new_trainer_appointment_path(@trainer) %>
    <% else %>
      <% appointment = current_user.client.appointments.find_by(trainer_id: @trainer.id, client_id: current_user.client.id) %>
      <% if appointment.present? %>
        <% if appointment.confirmed.nil? %>
          <p>Please wait for the trainer to confirm your appointment.</p>
        <% elsif appointment.confirmed? and appointment.client_id == current_user.client.id %>
          <p>Hello <%= current_user.client.name %>, drop your message here...<%= link_to "Chat", trainer_private_chat_path(@trainer), class: "chat-button" %><p>
          
        <% end %>
      <% end %>
    <% end %>
  <% end %>

  <p style="font-weight: bold; margin-top: 20px">Rating: <%= @my_rating %><br>
  <% if current_user.role == "trainer" %>
    <%= link_to 'Edit Your Profile', edit_trainer_path(@trainer) %> <br>
    <%= link_to "Pending Appointments", pending_appointments_path(@trainer)%><br>
    <%= link_to 'My Posts', trainer_posts_path(@trainer) %><br>
    <%= link_to "CREATE POST", new_trainer_post_path(@trainer) %><br>
    <%= link_to "My Clients", my_clients_path(@trainer)%><br>
    <%= link_to "View All Clients Available", clients_path %><br>
    <%= button_to "Log Out", destroy_user_session_path, method: :delete, data: { confirm: "Are you sure you want to log out?" } %>
  <% else %>
    <%= link_to 'My Posts', trainer_post_path(@trainer) %><br>
    <% unless current_user.client.ratings.exists?(trainer_id: @trainer.id) %>
      <%= form_with model: Rating.new, url: trainer_ratings_path(@trainer) do |form| %>
        <%= form.hidden_field :trainer_id, value: @trainer.id %>
        <label for="rating_value">Rate Trainer (0 to 5):</label>
        <%= form.select :value, (0..5).to_a, prompt: "Select rating" %>
        <%= form.submit "Submit Rating" %>
      <% end %>
    <% else %>
      <% rating = current_user.client.ratings.find_by(trainer_id: @trainer.id) %>
      <%= link_to "Update Rating", edit_trainer_rating_path(@trainer.id,rating.id), method: :put %>
    <% end %>
    <div class="stick">
      <%= link_to "Back to Feeds", trainers_path %><br>
    </div>
  <% end %>
</div>

app/views/trainers/show_clients.html.erb
<ul>
<div>
  <% @all_clients.each do |c| %>

    <li><p>Name: <%= link_to c.name, client_path(c) %></p></li><br>
  <% end %>
</div>
</ul>

<%= link_to 'Back to Profile', trainer_path(@trainer.id) %>

app/views/trainers/show_pendings.html.erb
<% if @appointments.any? %>
    <% @appointments.each do |a| %>
        <div>
        <p>Name: <%= link_to Client.find(a.client_id).name, client_path(Client.find(a.client_id)) %></p>
        <%= link_to "Confirm Appointment", confirm_appointment_path(a) %><pre> or </pre> 
        <%= link_to "Reject Appointment", reject_appointment_path(a), method: :delete %>
        </div>
        <hr>
    <% end %>
    <%= link_to 'Back to Profile', trainer_path(@trainer) %>
<% else %>
    <h1>NO Pending Appointments</h1>
    <%= link_to 'Back to Profile', trainer_path(@trainer) %>
<% end %>

app/views/trainers/update.html.erb
<h1>Trainers#update</h1>
<p>Find me in app/views/trainers/update.html.erb</p>