config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'messages/new'
  get 'messages/index'
  get 'rooms/index'
  get 'chats/show'
  get 'ratings/new'
  get 'ratings/create'
  get 'ratings/update'
  # get 'comments/create'
  # get 'comments/destroy'
  root to: "homes#index"
  get 'appointments/new'
  get 'appointments/create'
  get 'posts/new'
  get 'posts/create'
  get 'posts/show'

  get '/clients/:client_id/My_Trainers', to: 'clients#show_trainers', as: "my_trainers"
  get "/client/:client_id", to: "chats#private_chat", as: "client_private_chat"
  get "/trainer/:trainer_id", to: "chats#private_chat", as: "trainer_private_chat"
  devise_for :users
  
  # devise_scope :users do
  #    get 'users/:id', to: 'registrations#show', as: 'user'
  # end

 resources :rooms do
  resources :messages
 end
  
resources :clients
# resources :trainers
resources :trainers do
  resources :appointments
  resources :ratings
  resources :posts do
    resources :comments
  end
end

  # resources :trainers do
    
  # end

  resources :appointments, only: [] do
    member do
      get :confirm
      delete :reject
      delete :cancel
    end
  end
  get '/trainers/:trainer_id/Pending_Appointments', to: 'trainers#show_pendings', as: "pending_appointments"
  get '/trainers/:trainer_id/My_Clients', to: 'trainers#show_clients', as: "my_clients"
  delete '/trainers/sign_out', to: 'devise/sessions#destroy', as: :trainers_sign_out
  
  get 'user/:id', to: 'trainers#show', as: 'user'
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
 
  # Defines the root path route ("/")
  # root "articles#index"
  
end

app/models/ability.rb
class Ability
  include CanCan::Ability
  def initialize(user)
    if user.client?
      can :manage, Client
      can :read, Trainer
      can [:create, :update], Rating
      can [:create, :read, :destroy], Comment
      can :create, Appointment
    elsif user.trainer?
      can :manage, Trainer
      can :manage, Post
      can [:read, :destroy], Comment
      can :read, Client
      can [:confirm, :reject], Appointment
    end
  end
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :client
  belongs_to :trainer
end

app/models/client.rb
class Client < ApplicationRecord
  belongs_to :user
  has_many :appointments, dependent: :destroy
  has_many :ratings, dependent: :destroy
  has_many :rated_trainers, through: :ratings, source: :trainer
  has_one_attached :profile
  
  validates :name, presence: true, uniqueness: true
  validates :phone_number, numericality: true, length: { is: 10, messages: "phone number must contain 10 digits" }
  validates :age, numericality: true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  validates :comment, presence: true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room
  after_create_commit { broadcast_append_to self.room }
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :trainer
  has_many :comments, dependent: :destroy
  has_many_attached :images
  validates :title, presence: true
end

app/models/rating.rb
class Rating < ApplicationRecord
  belongs_to :client
  belongs_to :trainer
end

app/models/room.rb
class Room < ApplicationRecord
  validates_uniqueness_of :name
  scope :public_rooms, -> { where(is_private: false) }
  after_create_commit { broadcast_append_to "rooms" }
  has_many :messages, dependent: :destroy

end

app/models/trainer.rb
class Trainer < ApplicationRecord
  belongs_to :user
  has_many :posts, dependent: :destroy
  has_many :appointments, dependent: :destroy
  has_one_attached :profile
  has_many :ratings, class_name: "Rating", dependent: :destroy
  has_many :rating_clients, through: :ratings, source: :client
  
  validates :name, presence: true, uniqueness: true
  validates :phone_number, numericality: true, length: { is: 10, messages: "phone number must contain 10 digits" }
  validates :age, numericality: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  scope :all_except, ->(user) { where.not(id: user) }
  after_create_commit { broadcast_append_to "users" }
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable
         
  enum role: {client: 0, trainer: 1}

  has_one :trainer, dependent: :destroy
  has_one :client, dependent: :destroy
  has_many :messages, dependent: :destroy
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/trainers_helper.rb
module TrainersHelper
end

app/views/layouts/_navbartrainer.html.erb
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <style>
    .menu-btn {
        background-color: #040008;
        color: white;
        padding: 16px;
        font-size: 20px;
        font-weight: bolder;
        font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
        border: none;
    }

    .dropdown-menu {
        position: relative;
        display: inline-block;
    }

    .menu-content {
        display: none;
        position: absolute;
        background-color: #017575;
        min-width: 160px;
        z-index: 1;
    }

    nav {
        background-color: black;
    }

    .links,
    .links-hidden {
        display: inline-block;
        color: rgb(255, 255, 255);
        padding: 12px 16px;
        text-decoration: none;
        font-size: 18px;
        font-weight: bold;
    }

    .links-hidden {
        display: block;
    }

    .links {
        display: inline-block;
    }

    .links-hidden:hover,
    .links:hover {
        background-color: rgb(8, 107, 46);
    }

    .dropdown-menu:hover .menu-content {
        display: block;
    }

    .dropdown-menu:hover .menu-btn {
        background-color: #3e8e41;
    }

 
    </style>
    <nav>
    <%# if current_user.client or current_user.trainer %>
        <% if current_user.role == "client" %>
            <a class="links">
            <%= link_to "HOME", client_path(current_user), {:style=>'color:#FFFFFF;', :class => "css_class"} %>
            </a>  
            
            <a class="links">
            <%#= link_to "My Trainers", my_trainers_path(current_user.client), {:style=>'color:#FFFFFF;', :class => "css_class"} %>
            </a>

            <a class="links">
            <%#= link_to "All Trainers", trainers_path, {:style=>'color:#FFFFFF;', :class => "css_class"} %>
            </a>

            <div class="dropdown-menu">
                <%= button_to "LOG OUT", destroy_user_session_path, :method => :delete,
                :data => { :no_turbolink => true} %></>
            </div>
        <% else %>
            <a class="links">
            <%= link_to "HOME", trainer_path(current_user), {:style=>'color:#FFFFFF;', :class => "css_class"} %>
            </a>

            <a class="links">
            <%#= link_to 'My Posts', trainer_posts_path(current_user.trainer) %>
            </a>

            <a class="links">
            <%#= link_to "CREATE POST", new_trainer_post_path(current_user.trainer), {:style=>'color:#FFFFFF;', :class => "css_class"} %>
            </a>

            <a class="links">
            <%#= link_to "Pending Appointments", pending_appointments_path(current_user.trainer)%>
            </a>
            
            <div class="dropdown-menu">
                <%= button_to "LOG OUT", destroy_user_session_path, :method => :delete,
                :data => { :no_turbolink => true} %>
            </div>
        <% end %>
        <%# end %>
    </nav>

app/views/layouts/_new_message_form.html.erb
<div class="form-group msg-form">
  <%= form_with(model: [@single_room ,@message], remote: true, class: "d-flex" ) do |f| %>
    <%= f.text_field :content, id: 'chat-text', class: "form-control msg-content", autocomplete: 'off' %>
    <%= f.submit data: { disable_with: false }, class: "btn btn-primary" %>
  <% end %>
</div>

app/views/layouts/_new_room_form.html.erb
<%= form_with(model: @room, remote: true, class: "d-flex" ) do |f| %>
  <%= f.text_field :name, class: "form-control", autocomplete: 'off' %>
  <%= f.submit data: { disable_with: false } %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Future You</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <style>
      <%= ".msg-#{current_user&.id}" %> {
      background-color: #007bff !important;
      padding: 10px;
      }
      <%= ".cont-#{current_user&.id}" %> {
      display: flex;
      justify-content: flex-end
      }
    </style>

  </head>

  <body>
    <% if user_signed_in? %>
      <% if current_user.client or current_user.trainer  %>
       <%= render "layouts/navbartrainer" %>
    <%#= link_to "chats", rooms_path %>
    <% end %>
    <% end %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>